feat(#945): change es analyzers using environment variables
argilla-io/argilla pull request #1022
Opened 2022-01-24 13:41 UTC by frascuchon

Since rubrix stops using index template for dataset records index creation (See #1018), there is no way to customize the text fields analyzer.

This PR includes a basic mechanism to change the es analyzers. In the future, this parameters could be as part of dataset settings when creating a new dataset.

2022-01-24 13:53 UTC, dvsrepo requested changes

2022-01-24 13:53 UTC, dvsrepo commented on docs/getting_started/advanced_setup_guides.rst
> +As default, for index text fields, rubrix use the `standard` analyzer and the `whitespace` for accurate
```suggestion
By default, for indexing text fields, Rubrix uses the `standard` analyzer for general search and the `whitespace` analyzer for more exact queries (required by certain rules in the weak supervision module).
```

2022-01-24 13:53 UTC, dvsrepo commented on docs/getting_started/advanced_setup_guides.rst
> +text searches. If those analyzers does not feat your data, you can change by using the environment variables
```suggestion
 If those analyzers don't fit your use case, you can change them using the following environment variables:
```

2022-01-24 13:53 UTC, dvsrepo commented on docs/getting_started/advanced_setup_guides.rst
> +customized analyzer, you should create it inside an index_template matching the rubrix index names (`.rubrix*.records-v0),
```suggestion
customized analyzer, you should create it inside an index_template matching Rubrix index names (`.rubrix*.records-v0),
```

2022-01-24 13:53 UTC, dvsrepo commented on docs/getting_started/advanced_setup_guides.rst
> +and then provide the analyzer name using the convenient environment variable.
```suggestion
and then provide the analyzer name using the specific environment variable.
```

2022-01-25 10:02 UTC, dcfidalgo approved these changes

2022-01-25 18:08 UTC, merged