fix(#982): extends search area
argilla-io/argilla pull request #1112
Opened 2022-02-08 12:04 UTC by leiyre

fix #982

This PR Extends search area. Search area + filters are adjusted to the "record column width"

2022-02-08 12:32 UTC, frascuchon requested changes
Cannot see filters properly 


<img width="623" alt="Screenshot 2022-02-08 at 13 32 00" src="https://user-images.githubusercontent.com/2518789/152987647-f5a2b65a-c2ea-44ea-b4e7-2390b26c17f9.png">

2022-02-08 13:02 UTC, leiyre commented
oops right, that's why it was limited to 450px. @Amelie-V how can we deal with this? maybe open the filters to the left?

2022-02-09 09:46 UTC, Amelie-V commented
@leiyre I would recommend extending the current search box 200 px more. In that way Sort modal should fit on the right side.

2022-02-09 13:34 UTC, frascuchon approved these changes

2022-02-09 13:34 UTC, merged