fixing typo
argilla-io/argilla pull request #1184
Opened 2022-02-18 14:39 UTC by leireropl

2022-02-18 14:41 UTC, leireropl commented
I am going to do one more commit with new changes

2022-02-18 15:15 UTC, leireropl commented
Regarding the spaCy tutorial, I was wondering whether the section I placed the HF information is the most suitable. At first, I thought that the end of the tutorial would be the best place, but it doesn't make sense (people will have uploaded everything to Rubrix by then). 

Some clarifications have been made for this part, but if you think I should change it, just say it ;)

2022-02-21 15:29 UTC, dvsrepo requested changes
Hi @leireropl , it looks better but I have some suggestions. The main idea is that users can skip part of the tutorial for building the dataset (which is time consuming) so we should be very clear: if you want to skip steps X and Y, you can use this dataset from the Hub.... and go directly to step W. If it's necessary we can add numbers to the sections.

- Showing the info before the user downloads the raw dataset, uses the pipeline and logs into Rubrix. The idea is to be very explicit: INFO( If you want to skip the next N steps, you can do the following:) and then show a cell with all the necessary for reading the Rubrix dataset from the hub and logging it into Rubrix.
- The Bonus part I would call it Appendix and I would explain how to upload the dataset more generally (without the rubrix/{dataset_name}. Here my recommendation is to use rb.load() instead of the records because we don't know the order in which the user is running the notebook so `records` my not be available.
- For the spaCy tutorial I would upload the imdb one for the hub and make sure the Gutenberg one includes the predictions of both model (trf and the other one).

2022-02-22 14:20 UTC, leireropl commented
Hi,

I made some changes to the files. I think I got what you meant (more or less), let me know if this is OK.

2022-02-23 10:58 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "dataset_ds.push_to_hub(\"Rubrix/sentiment-banking\")"
```suggestion
    "dataset_ds.push_to_hub(\"rubrix/sentiment-banking\")"
```

2022-02-23 10:58 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "dataset_ds = load_dataset(\"Rubrix/sentiment-banking\", split=\"train\")\n",
```suggestion
    "dataset_ds = load_dataset(\"rubrix/sentiment-banking\", split=\"train\")\n",
```

2022-02-23 17:40 UTC, frascuchon commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "dataset_ds.push_to_hub(\"Rubrix/sentiment-banking\")"
"Rubrix" or "rubrix" @dcfidalgo ?

2022-02-23 20:07 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "dataset_ds.push_to_hub(\"Rubrix/sentiment-banking\")"
our organization at HF is called "rubrix", so it should be "rubrix"

2022-02-24 23:35 UTC, merged