feat(#1144) allow multilabel records in weak supervision
argilla-io/argilla pull request #1233
Opened 2022-03-08 15:18 UTC by leiyre

see #1144

2022-03-08 16:15 UTC, frascuchon requested changes
Precision, correct and incorrect metrics are missing. 

<img width="1568" alt="Screenshot 2022-03-08 at 17 13 46" src="https://user-images.githubusercontent.com/2518789/157278575-614fb369-7e7e-43e5-b633-cff25f4f78f5.png">

The same dataset with master branch is still working.

Also, labels values in field are misaligned.

2022-03-08 16:15 UTC, frascuchon commented on frontend/components/text-classifier/labeling-rules/RuleLabelsDefinition.vue
> +        return "This query with this labels are already saved as rule";
The message should be built depending on the number of labels the rule have defined. Should keep the singular form if the number of labels is equal to one (even for multi-label)

2022-03-11 13:42 UTC, frascuchon commented on frontend/components/text-classifier/labeling-rules/RuleLabelsDefinition.vue
> +        return `This query with this ${this.dataset.isMultiLabel ? 'labels' : 'label'} are already saved as rule`;
I think it should be better to use the number of labels in rule. Even for multi-label rules definition you could define a single label.

2022-03-14 09:37 UTC, frascuchon commented
- No rules defined but the message "This query with this labels are already saved as rule" is shown

![Screenshot 2022-03-14 at 10 33 46](https://user-images.githubusercontent.com/2518789/158144793-3c7894c0-6f99-4c96-8907-42b31773df00.png)

2022-03-14 11:12 UTC, dvsrepo commented
> * No rules defined but the message "This query with this labels are already saved as rule" is shown
> 
> ![Screenshot 2022-03-14 at 10 33 46](https://user-images.githubusercontent.com/2518789/158144793-3c7894c0-6f99-4c96-8907-42b31773df00.png)

@leiyre also the message should be these labels and not this labels. Thanks!!

2022-03-14 22:08 UTC, frascuchon commented
Adding a label to an existing rule don't refresh the labes in rules summary

<img width="1047" alt="Screenshot 2022-03-14 at 23 06 58" src="https://user-images.githubusercontent.com/2518789/158269153-b8d71daf-6928-41a1-ac2d-1116396e366e.png">

<img width="1544" alt="Screenshot 2022-03-14 at 23 07 50" src="https://user-images.githubusercontent.com/2518789/158269167-fcabbbe9-26f9-4be6-a7a5-a1a1992ce039.png">

2022-03-15 14:03 UTC, frascuchon commented
1. select an already created rule from rule summary
2. The precision and correct/incorrect metrics show the rule metrics 
3. change the rule query -> related metrics are reset.
4. Precision and correct/incorrect metrics are not computed.

![Screenshot 2022-03-15 at 15 00 42](https://user-images.githubusercontent.com/2518789/158394935-8a18e13b-7527-46a1-9af1-b37e464ce43f.png)

2022-03-16 21:32 UTC, frascuchon approved these changes

2022-03-16 21:32 UTC, merged