fix(#1368): set color of the TokenClassification entities
argilla-io/argilla pull request #1388
Opened 2022-04-07 07:29 UTC by leiyre

fix #1368

This PR changes the number of color entities from 50 to infinity

2022-04-07 07:46 UTC, frascuchon requested changes

2022-04-07 07:46 UTC, frascuchon commented on frontend/models/TokenClassification.js
> +      const colorLimit = 50;
This magic number (50) should be used where the color palette is defined.

2022-04-07 08:08 UTC, frascuchon commented
Also, with these changes, maybe we could consider decreasing the number of available colors for entity tags?

cc @leiyre @Amelie-V @dvsrepo

2022-04-07 13:48 UTC, leiyre commented
> Also, with these changes, maybe we could consider decreasing the number of available colors for entity tags?
> 
> cc @leiyre @Amelie-V @dvsrepo

Yes, we can experiment with more contrasting colors by limiting the number or we can also pass a list of custom colors.

2022-04-07 15:21 UTC, frascuchon commented on frontend/specs/components/token-classification/results/__snapshots__/EntitiesSelector.spec.js.snap
> +<li tabindex="0" class="entities__selector__option color_NaN"><span>CARDINAL</span> <span class="entity__sort-code">[2]</span></li>
`color_NaN` are expected results? This snapshot shouldn't have changed

2022-04-07 15:26 UTC, frascuchon commented
After deploy changes the webapp  is not accessible and I see the following error:
<img width="1448" alt="Screenshot 2022-04-07 at 17 25 43" src="https://user-images.githubusercontent.com/2518789/162235425-54bd597c-47b7-4de7-9f4c-1440e9bcf35a.png">

2022-04-11 12:25 UTC, frascuchon approved these changes

2022-04-11 12:26 UTC, merged