feat(#1132): Introduce async version of our API
argilla-io/argilla pull request #1391
Opened 2022-04-07 09:36 UTC by dcfidalgo

Closes #1132

TODO:
- [ ] tests

2022-04-07 16:11 UTC, dcfidalgo commented
@frascuchon I did the refactoring discussed during the call. What's missing is updating the tests, documentation/docstrings, and maybe an improved behavior of the monitoring module (several retries, some automatic chunking, error messages), but maybe this can also be tackled in a separate PR.

2022-04-13 12:05 UTC, frascuchon commented
Since I didn't find a use case just using async `log_async` directly, I've included a `background` argument in the `log` function that could simplify the custom data monitoring.

```python
rb.log(
    name="monitor-dataset",
    records=rb_records,
    background=True, 
)

```

I've also included a minimal example in monitoring guides using bentoML + spaCy.

Please, feel free to add your comments

@dvsrepo @dcfidalgo

2022-04-22 10:00 UTC, dvsrepo requested changes

2022-04-22 10:00 UTC, dvsrepo commented on docs/guides/monitoring.ipynb
> +    "You can monitor your own models without latency by using the `background` param in rb.log\n",
```suggestion
    "You can monitor your own models without adding a response delay by using the `background` param in rb.log\n",
```

2022-04-22 10:00 UTC, dvsrepo commented on docs/guides/monitoring.ipynb
> +    "Let show an example using bentoml + spacy NER:\n"
```suggestion
    "Let's see an example using [BentoML](https://www.bentoml.com/) with a spaCy NER pipeline:\n"
```

2022-04-22 14:30 UTC, dvsrepo submitted a review, later dismissed

2022-04-25 10:12 UTC, dcfidalgo commented
I removed the `Api._log` method since with the new implementation there is no need for this helper method. The example in the monitor guide looks good to me, I just added a small example in the docstring of the `rb.log` method to simply show the effect of setting `background=True`. Also improved a bit this docstring.

From my side, this is good to go.

2022-04-25 16:06 UTC, frascuchon approved these changes
YEAH!

2022-04-25 16:07 UTC, merged