docs: Add active learning with small text and listener tutorial
argilla-io/argilla pull request #1585
Opened 2022-06-27 16:50 UTC by dcfidalgo

2022-06-27 17:11 UTC, frascuchon commented
@dcfidalgo, please review the PR #1586 before finishing the tutorial. We should change the query definition in this tutorial since record indices are hardly related to active learning batch. 

The `active_learner.query` and `active_learner.update` have a highly coupled, hardly linked to the current batch step. A way to resolve this could be to include the expected batch id as a query param and update it inside the listener action. Let's talk if you want.

2022-07-04 12:54 UTC, dcfidalgo commented
See the built docs here: https://rubrix.readthedocs.io/en/docs-add_small_text_with_listener_tutorial/tutorials/active_learning_with_small_text.html

TODO:
 - [ ] Add video

2022-07-06 16:28 UTC, frascuchon requested changes

2022-07-06 16:28 UTC, frascuchon commented on docs/tutorials/active_learning_with_small_text.ipynb
> +    "For this, we will use the [listener decorator](../reference/python/rubrix_listener.rst#rubrix.listeners.listener) from Rubrix. \n",
This link is broken in the documentation.

See [compiled docs](https://rubrix.readthedocs.io/en/docs-add_small_text_with_listener_tutorial/tutorials/active_learning_with_small_text.html#Rubrix-and-you:-the-perfect-oracle)

2022-07-06 20:40 UTC, dcfidalgo commented on docs/tutorials/active_learning_with_small_text.ipynb
> +    "For this, we will use the [listener decorator](../reference/python/rubrix_listener.rst#rubrix.listeners.listener) from Rubrix. \n",
done

2022-07-07 10:22 UTC, frascuchon approved these changes

2022-07-07 10:23 UTC, merged