feat(Client): expose client extra headers in init function
argilla-io/argilla pull request #1715
Opened 2022-09-13 14:58 UTC by frascuchon

Closes #1706

2022-09-16 07:12 UTC, frascuchon commented
@dvsrepo just review the arg naming and doc string, pls.

https://github.com/recognai/rubrix/pull/1715/files#diff-6b8ac5652e75b4d467e0bab452972dd441064ffc7a694a201fd3fb4b0530ba7eR116

2022-09-21 08:14 UTC, dvsrepo commented on src/rubrix/client/api.py
> +            extra_headers: Extra http headers sent to the server. Default: `None`
Could we add a sentence explaining a little more why this is useful? Like "you can use this for .. " I know most people that needs this will know, but even with a simple example on usefulness could help users to better understand this parameter

2022-09-21 13:20 UTC, frascuchon commented on src/rubrix/client/api.py
> +            extra_headers: Extra http headers sent to the server. Default: `None`
I've included changes. Take a look pls.

2022-09-21 14:05 UTC, frascuchon commented
You can also check the generated documentation: https://rubrix.readthedocs.io/en/feat-customize-client-headers/

2022-09-21 14:16 UTC, dvsrepo requested changes

2022-09-21 14:16 UTC, dvsrepo commented on src/rubrix/client/api.py
> +            extra_headers: Extra http headers sent to the server. You can use this for customize
```suggestion
            extra_headers: Extra HTTP headers sent to the server. You can use this to customize
```

2022-09-21 14:16 UTC, dvsrepo commented on src/rubrix/client/api.py
> +                client requests if you have some security restrictions. Default: `None`.
```suggestion
                the headers of Rubrix client requests, like additional security restrictions. Default: `None`.
```

2022-09-22 08:00 UTC, dvsrepo approved these changes

2022-09-22 08:01 UTC, merged