feat(Datasets): delete records by query
argilla-io/argilla pull request #1721
Opened 2022-09-15 21:16 UTC by frascuchon

Closes #1048

2022-09-20 13:42 UTC, frascuchon commented
@dvsrepo Could you please review the docstring?

2022-09-20 15:55 UTC, dvsrepo requested changes

2022-09-20 15:55 UTC, dvsrepo commented on src/rubrix/client/api.py
> +            The total of matched records and real number of processed errors. These numbers could not
```suggestion
            The total number of matched records and real number of processed errors. These numbers could not
```

2022-09-20 15:55 UTC, dvsrepo commented on src/rubrix/client/api.py
> +                If `True`, matched records won't be delete. Instead of that, they will be marked
```suggestion
                If `True`, matched records won't be deleted. Instead, they will be marked
```

2022-09-21 08:06 UTC, dvsrepo approved these changes

2022-09-21 12:43 UTC, merged