Badges!
argilla-io/argilla pull request #209
Opened 2021-07-13 17:13 UTC by ignacioct

Closes #208 

Feel free to suggest a different disposition of badges! Also, I was very surprised by how many Docker pulls we have, but I don't exactly know how they are measured. 

To obtain a first Codecov coverage value we must merge to master, as I've configured it to do so. Once we merge, I will check if Codecov is taking correctly our data, which it must!

2021-07-13 19:02 UTC, ignacioct commented
Well, after fighting a little bit against Github Actions, I'm obtaining the following error on the calculation of the coverage report.

```
=========================== short test summary info ============================
379
ERROR temporal/test_app.py
380
ERROR tests/test_init.py
381
ERROR tests/test_log.py
382
ERROR tests/test_logging.py
383
ERROR tests/client/test_asgi.py
384
ERROR tests/client/test_client.py
385
ERROR tests/client/test_models.py
386
ERROR tests/server/datasets/test_api.py
387
ERROR tests/server/datasets/test_dao.py
388
ERROR tests/server/datasets/test_model.py
389
ERROR tests/server/info/test_api.py
390
ERROR tests/server/snapshots/test_api.py
391
ERROR tests/server/text_classification/test_api.py
392
ERROR tests/server/text_classification/test_model.py
393
ERROR tests/server/token_classification/test_api.py
394
ERROR tests/server/token_classification/test_model.py
395
!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!
396
============================== 16 errors in 1.66s ==============================
397
Error: Process completed with exit code 2.
```

@frascuchon , could these tests be the ones that need a pre-existing environment to work? How can we make so CodeCov accepts them?

2021-07-14 09:39 UTC, dcfidalgo requested changes
Nice!! Just a small comment about efficiency, I think we should avoid running our test suite twice.

2021-07-14 09:39 UTC, dcfidalgo commented on .github/workflows/ci.yml
> +          pytest --cov=./
I think we should avoid running our test suite twice, see the job above. So maybe include the coverage generation/uploading in the job above.

2021-07-15 10:47 UTC, ignacioct commented
I've submitted a ticket to the Support Forum os Codecov, as I'm totally lost on why our test coverage report is not being correctly uploaded.

2021-07-15 15:02 UTC, frascuchon commented
Nice work !!! 

I've testing badges info and I found code coverage is not reported:

<img width="853" alt="Screenshot 2021-07-15 at 17 00 40" src="https://user-images.githubusercontent.com/2518789/125810380-b83bcffd-f6aa-40f4-bd68-e19a507315ad.png">


Maybe the generated coverage xml report and the  configured files should be the same? 

<img width="498" alt="Screenshot 2021-07-15 at 16 59 29" src="https://user-images.githubusercontent.com/2518789/125810521-5f7f571f-7fa3-4bc4-989c-d45e7d749da8.png">


<img width="813" alt="Screenshot 2021-07-15 at 16 59 03" src="https://user-images.githubusercontent.com/2518789/125810538-3360c12b-7fdc-4233-92c3-7318064bfd9c.png">

2021-07-26 13:21 UTC, dcfidalgo approved these changes

2021-07-26 13:28 UTC, dvsrepo requested changes

2021-07-26 13:28 UTC, dvsrepo commented on README.md
> +<h3 align="center">Explore, label, and monitor data for AI projects</h3>
I'd place this h3 before the badges, if possible

2021-07-26 14:19 UTC, dcfidalgo commented
Ok, i will merge this PR, which should upload a first cov report. The coverage is quite bad, mainly because of the `sdk` folder. Since the sdk code is created automatically (i think almost entirely), i am not sure if we need tests for it. We could exclude it in the cov report, @frascuchon what do you think?

2021-07-26 14:20 UTC, merged

2021-07-28 10:07 UTC, frascuchon commented
We could filter sdk folder for coverage reports. Can we configure folder/module exclusion for codecov @dcfidalgo?