feat: Show number of records when similarity filter is applied
argilla-io/argilla pull request #2226
Opened 2023-01-18 13:38 UTC by leiyre

# Description

This PR changes the number of records in the query to get 50 results and includes an option in the base pagination to display on page with the number of records

Closes ##2197

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

**How Has This Been Tested**

Please describe the tests that you ran to verify your changes. And ideally reference `tests`.

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [ ] follows the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I added comments to my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-01-18 15:39 UTC, keithCuniah approved these changes

2023-01-20 15:14 UTC, frascuchon requested changes
Changes here will be included in patch release. Please point to the main branch and be sure that only affected files are included
 cc @leiyre

2023-01-22 22:01 UTC, frascuchon commented
I've already restored some of the files but some extra work is needed in the frontend part. 

@leiyre please, take a look into them ASAP

2023-01-23 15:19 UTC, frascuchon approved these changes

2023-01-23 15:20 UTC, merged