Integrate datasets crud endpoints
argilla-io/argilla pull request #2510
Opened 2023-03-09 08:26 UTC by frascuchon

This is a PR where datasets integration will be applied.

2023-03-10 16:53 UTC, jfcalvo requested changes

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/apis/v0/handlers/datasets.py
> +    user: User = Security(auth.get_current_user),
```suggestion
    current_user: User = Security(auth.get_current_user),
```

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/apis/v0/handlers/datasets.py
>      dataset = datasets.create_dataset(user=user, dataset=request)
```suggestion
    dataset = datasets.create_dataset(user=current_user, dataset=request)
```

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/apis/v0/handlers/text_classification_dataset_settings.py
> +        user: User = Security(auth.get_current_user),
```suggestion
        current_user: User = Security(auth.get_current_user),
```

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/apis/v0/handlers/text_classification_dataset_settings.py
> +        user: User = Security(auth.get_current_user),
```suggestion
        current_user: User = Security(auth.get_current_user),
```

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/apis/v0/handlers/token_classification_dataset_settings.py
> +        user: User = Security(auth.get_current_user),
```suggestion
        current_user: User = Security(auth.get_current_user),
```

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/apis/v0/handlers/token_classification_dataset_settings.py
> +        user: User = Security(auth.get_current_user),
```suggestion
        current_user: User = Security(auth.get_current_user),
```

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/apis/v0/handlers/token_classification_dataset_settings.py
> +        user: User = Security(auth.get_current_user),
```suggestion
        current_user: User = Security(auth.get_current_user),
```

2023-03-10 16:53 UTC, jfcalvo commented on src/argilla/server/policies.py
> +        return lambda actor: actor.is_admin or (is_get_allowed(actor) and actor.username == dataset.created_by)
I believe we need to reduce complexity here someway. Let's discuss it.

Apart from that now that we have a ORM User instance on all handlers we can change all the policies from `actor.role == UserRole.admin` to `actor.is_admin`

2023-03-10 16:58 UTC, frascuchon commented on src/argilla/server/policies.py
> +        return lambda actor: actor.is_admin or (is_get_allowed(actor) and actor.username == dataset.created_by)
Yes, the way policy actions are compounded is not quite simple.

2023-03-13 08:55 UTC, jfcalvo approved these changes

2023-03-13 09:04 UTC, merged