Review annotator policies for dataset settings
argilla-io/argilla pull request #2547
Opened 2023-03-15 11:40 UTC by frascuchon

For an annotator, dataset settings are visible in read-only mode.

This PR adds task dataset settings-related policies and uses them in dataset settings-related actions.

Also, new tests are added to test this functionality.

2023-03-15 12:42 UTC, jfcalvo commented on src/argilla/server/policies.py
> +class TaskDatasetSettingsPolicy:
Why `TaskDatasetSettingsPolicy` instead of `DatasetSettingsPolicy`?

2023-03-15 14:12 UTC, jfcalvo requested changes

2023-03-15 14:12 UTC, jfcalvo commented on src/argilla/server/services/datasets.py
> +                "You don't have the necessary permissions to list settings for this dataset. "
```suggestion
                "You don't have the necessary permissions to list settings for this dataset."
```

2023-03-15 14:12 UTC, jfcalvo commented on src/argilla/server/services/datasets.py
> +                "You don't have the necessary permissions to save settings for this dataset. "
```suggestion
                "You don't have the necessary permissions to save settings for this dataset."
```

2023-03-15 14:12 UTC, jfcalvo commented on src/argilla/server/services/datasets.py
> +                "You don't have the necessary permissions to delete settings for this dataset. "
```suggestion
                "You don't have the necessary permissions to delete settings for this dataset."
```

2023-03-15 14:12 UTC, jfcalvo commented on tests/server/text_classification/test_api_settings.py
> +    assert response.status_code == 200
Not sure if there is an easy solution for this but you are testing not only the save settings endpoint but the dataset creation as well.

The ideal scenario is to only test the specific endpoint and create the dataset manually.

The same happen with the rest of tests.

2023-03-15 15:48 UTC, frascuchon commented on tests/server/text_classification/test_api_settings.py
> +    assert response.status_code == 200
Please, fill free to add the test setup using the elasticsearch client to create the document directly.

These tests are testing user flows more than simple endpoint actions. It's faster and gives us the confidence to check the flow interactions

2023-03-15 15:49 UTC, frascuchon commented on src/argilla/server/policies.py
> +class TaskDatasetSettingsPolicy:
At the moment, `DatasetSettingsPolicy` name fits better.  I will change it

2023-03-15 16:57 UTC, jfcalvo commented on tests/server/text_classification/test_api_settings.py
> +    assert response.status_code == 200
> These tests are testing user flows more than simple endpoint actions. It's faster and gives us the confidence to check the flow interactions

Sure and that's fine, but in that case I would move those tests to some special folder like `test_api_flows` or something similar (and left regular files for unit testing). We can talk about this if you want.

2023-03-16 09:55 UTC, jfcalvo approved these changes

2023-03-16 12:10 UTC, merged