fix: removed "context" reference from datasets prepare_for_training #…
argilla-io/argilla pull request #2610
Opened 2023-03-28 08:12 UTC by davidberenstein1957

# Description
Fixed missing context key.

Closes #2606 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested**

N.A.
**Checklist**

N.A.

2023-03-28 10:25 UTC, alvarobartt commented
Hi @davidberenstein1957! I'd say you also need to remove the `context` references in the unit tests at https://github.com/argilla-io/argilla/blob/29972416cf83869fb664d78f75e150c99f45ed51/tests/client/test_dataset.py#L346-L355 👍🏻

2023-03-28 10:26 UTC, alvarobartt commented on src/argilla/client/datasets.py
> -                    "context": ds_dict["context"],
Hi @davidberenstein1957! I'd say you also need to remove the `context` references in the unit tests at https://github.com/argilla-io/argilla/blob/29972416cf83869fb664d78f75e150c99f45ed51/tests/client/test_dataset.py#L346-L355 👍🏻

2023-03-28 10:28 UTC, alvarobartt commented on src/argilla/client/datasets.py
> -                    "context": ds_dict["context"],
As that's just failing for the `multilabel_textclassification_records` when testing the `DatasetForTextClassification`

2023-03-28 12:36 UTC, frascuchon commented on src/argilla/client/datasets.py
> -                    "context": ds_dict["context"],
Thanks @alvarobartt 

Also, something to add. For single-label records, we're adding all defined inputs in records instead of only the `text` one See https://github.com/argilla-io/argilla/blob/29972416cf83869fb664d78f75e150c99f45ed51/src/argilla/client/datasets.py#L744-L748

Not sure what should be the better approach, but I think we should align both cases

2023-03-28 12:36 UTC, frascuchon requested changes
See comments

2023-03-30 11:05 UTC, davidberenstein1957 commented
will be included here https://github.com/argilla-io/argilla/pull/2574

2023-03-30 11:05 UTC, closed without merging