style update messages
argilla-io/argilla pull request #2648
Opened 2023-04-04 13:28 UTC by keithCuniah

# Description
Update messages 

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

See #2626 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)
- [ ] Documentation update
- [x] Style

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A

**Checklist**

- [ ] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [ ] follows the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2023-04-04 13:49 UTC, frascuchon commented on CHANGELOG.md
> +- Update messages. See [#2648](https://github.com/argilla-io/argilla/pull/2648)
This message is not useful. Take in mind what is the purpose of the CHANGELOG.md file: show relevant changes between releases. `Update messages ...` says no much about a relevant change. Even more, we have the relevant change in previous entry: `Style updates for weak...` 
```suggestion
```

2023-04-04 13:50 UTC, frascuchon commented on .pre-commit-config.yaml
this file is not relevant to the PR, can you please remove it?

2023-04-04 13:51 UTC, frascuchon requested changes
review files and changelog please

2023-04-04 14:02 UTC, frascuchon commented on .pre-commit-config.yaml
We cannot remove the file, just the changes introduced here. This file exists, just restore the version from releases/1.6.0 branch, please

2023-04-04 18:29 UTC, tomaarsen requested changes

2023-04-04 18:29 UTC, tomaarsen commented on CHANGELOG.md
> +- Update messages for weak labelling and rule management toast. See [#2648](https://github.com/argilla-io/argilla/pull/2648)
```suggestion
- Style updates for weak labelling and adding feedback toast when delete rules. See [#2626](https://github.com/argilla-io/argilla/pull/2626) and [#2648](https://github.com/argilla-io/argilla/pull/2648)
```
My perspective is that these two items are sufficiently related that they can be "merged" to keep the changelog concise. I'll let @frascuchon make the decision though, he oversees the changelog at the moment.

2023-04-04 18:29 UTC, tomaarsen commented on frontend/components/text-classifier/labeling-rules/RuleLabelsDefinition.vue
> +        "To create new rules, you need al least two labels. <br />We highly recommend starting by annotating some records with these labels.",
```suggestion
        "To create new rules, you need at least two labels. <br />We highly recommend starting by annotating some records with these labels.",
```
Small typo here.

2023-04-04 18:29 UTC, tomaarsen commented on frontend/components/text-classifier/labeling-rules/RuleEmptyQuery.vue
>        messageNotLabels: `To create new rules, you need al least two labels.
```suggestion
      messageNotLabels: `To create new rules, you need at least two labels.
```

2023-04-05 07:27 UTC, frascuchon commented on CHANGELOG.md
> +- Update messages for weak labelling and rule management toast. See [#2648](https://github.com/argilla-io/argilla/pull/2648)
Fully agree with @tomaarsen

2023-04-05 07:58 UTC, nataliaElv commented on frontend/components/text-classifier/labeling-rules/RuleLabelsDefinition.vue
> +        "To create new rules, you need al least two labels. <br />We highly recommend starting by annotating some records with these labels.",
good catch! Thanks for spotting that 😄

2023-04-05 07:59 UTC, tomaarsen commented on frontend/components/text-classifier/labeling-rules/RuleLabelsDefinition.vue
> +        "To create new rules, you need al least two labels. <br />We highly recommend starting by annotating some records with these labels.",
😄

2023-04-05 08:54 UTC, tomaarsen approved these changes
Looks perfect! Thanks

2023-04-05 10:17 UTC, frascuchon approved these changes

2023-04-05 10:17 UTC, merged