Feat/users management
argilla-io/argilla pull request #272
Opened 2021-08-13 12:28 UTC by frascuchon

This PR normalizes user management and basic authentication. 

- Now, rubrix server enables user basic authentication 
- An default user/pass + api key is automatically configured if no auth setup
- Default api key and pass can be override using env vars
- User management based on basic yaml file
- rubrix client uses the default api key if no api key is provided.

TODO:

- Include user management documentation
- update App references in documentation
- Validate user data model

2021-08-13 12:29 UTC, frascuchon commented
I'll start a basic bullet documentation entry. 

@dvsrepo Where can I include the entry in the documentation?

2021-08-13 15:05 UTC, frascuchon commented
A minimal brief doc section is added.

@dvsrepo could you please, take a look?

2021-08-13 15:14 UTC, dvsrepo requested changes
Looks good to me! only thing left would be to transform it into rst

2021-08-13 15:14 UTC, dvsrepo commented on docs/getting_started/user_management.md
> +You can reload the rubrix service for refresh container:
```suggestion
You can reload the rubrix service to refresh the container:
```

2021-08-13 15:14 UTC, dvsrepo commented on docs/getting_started/user_management.md
> +If everything go well, you can use configured users in rubrix for data annotation
```suggestion
If everything went well, configured users can now log in and their annotations will be tracked with their usernames.
```

2021-08-16 07:45 UTC, frascuchon commented
@dvsrepo  you can check generated documentation [here](https://docs.rubrix.ml/en/feat-users_management/getting_started/setup%26installation.html#next-steps)

2021-08-16 09:31 UTC, dvsrepo commented
Looks good to me but maybe David can do a review and add a short introduction and some more wording for each of the steps, indicating when you want to / need to do each step. Also I'd a reference to where the provided  docker-compose is located

2021-08-16 16:06 UTC, dcfidalgo commented
I think we should merge the documentation with the "Advanced installation setup using docker" and simply call it "Advanced installation setup" or something like this. Maybe we can merge this PR as is, and then i provide a new PR with the merge and a revision of the "User managment" guide. @frascuchon If you are ok with this proposal, just merge this PR, then i will start working on the follow-up PR.

2021-08-16 16:19 UTC, merged