Fix: assignments tutorial bug
argilla-io/argilla pull request #2795
Opened 2023-04-27 11:31 UTC by nataliaElv

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #2793 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update

**Checklist**

- [x] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [ ] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2023-04-27 13:00 UTC, davidberenstein1957 commented on docs/_source/tutorials/notebooks/labelling-tokenclassification-basics.ipynb
> +    "for user, records in assignments.items():\n",
Hi Natalia, I think it makes more sense to first create a list of the total record and afterwards log all of them at once. Thank you:)

```python
assigned_records = []
for user, records in assignments.items():
    for r in records:
        r.metadata['user'] = user
        assigned_records.append(r)
rg.log(
    records=records,
    workspace='recognai',
    name='gutenberg_spacy-ner',
    tags={'with assignments': True}
)
```

2023-04-28 09:36 UTC, tomaarsen requested changes
It's not a very big deal, but can we normalize `rec` and `r` into `record` throughout this notebook? Especially for `for idx, rec in enumerate(chunk):` it's not immediately clear what "rec" entails if you're not familiar with the nomenclature of Argilla. 

`for r in records:` is clearer already, but I just don't like 1-letter variable names if we can avoid them.

Looks good otherwise!

2023-04-28 10:07 UTC, tomaarsen approved these changes
LGTM now

2023-04-28 10:14 UTC, tomaarsen approved these changes

2023-04-28 10:20 UTC, merged