Return FeedbackDataset URL on push
argilla-io/argilla pull request #3217
Opened 2023-06-17 11:44 UTC by krishnajalan

# Description

Return the URL of a FeedbackDataset that has been pushed either to Argilla or to the HuggingFace Hub, to let the user easily access the dataset and know where it has been pushed.

Argilla URL: <API_URL>/<DATASET_ID>/annotation-mode
HuggingFace Hub URL: https://huggingface.co/<REPO_ID>

Closes #3120 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Improvement (change adding some improvement to an existing functionality)

**Checklist**

- [x] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2023-06-19 06:55 UTC, davidberenstein1957 commented
Hi @krishnajalan, thanks for this PR! I asked @alvarobartt to review it because he is the mastermind behind the FeedBackdataset API. We do still need all tests to pass before merging though.

2023-06-19 07:07 UTC, alvarobartt commented
Hi @krishnajalan (thanks for tagging @davidberenstein1957!)

So that issue is being solved at #3216 (soon to be merged), as we recently included the `owner` role and somethings had to be changed, as there was no conflict during merge, but when running the unit tests on `develop` this error was raised. I'll let you know when the changes are applied so that you merge `develop` into this branch to fix the failing unit tests 😄

2023-06-19 07:15 UTC, alvarobartt requested changes
LGTM, just some minor comments and could you add some basic/simple unit tests to make sure that the returned URLs are formatted as expected? Thanks a lot @krishnajalan 🤗

2023-06-19 07:15 UTC, alvarobartt commented on src/argilla/client/feedback/dataset.py
> +            return f"{rg.active_client().http_client.base_url}/{argilla_id}/annotation-mode"
I think we should avoid calling the `rg.active_client()` more than once within the same function, so feel free to define a variable on top of this function named `client = rg.active_client()` and then re-use `client` e.g. this line should look like

```suggestion
            return f"{client.http_client.base_url}/{self.argilla_id}/annotation-mode"
```

2023-06-19 07:15 UTC, alvarobartt commented on src/argilla/client/feedback/dataset.py
>              self.argilla_id = argilla_id
I guess here we could also return the current URL e.g.

```suggestion
            self.argilla_id = self.argilla_id or argilla_id
```

2023-06-19 07:15 UTC, alvarobartt commented on src/argilla/client/feedback/dataset.py
> +    ) -> Union[str, None]:
And here there's no need to return `Union[str, None]`, but `str`, as previously we were not returning `None` as is, just not returning anything.

```suggestion
    ) -> str:
```

2023-06-19 07:15 UTC, alvarobartt commented on src/argilla/client/feedback/dataset.py
> +    ) -> Union[str, None]:
Same thing here if the change below to return the URL unless there's an exception is applied 👍🏻 

```suggestion
    ) -> str:
```

2023-06-19 07:16 UTC, alvarobartt commented
Also FYI @gabrielmbmb suggested to transition to `Union` over `Optional` to be more aligned with Python 3.10's `|` operator to define optional values, so we'll probably transition to e.g. `Union[str, None]` as you did in the code above, so great work! 🤗

2023-06-26 07:14 UTC, krishnajalan commented
hey @alvarobartt I have addressed the above comments take a look at changes.

2023-06-26 07:18 UTC, alvarobartt approved these changes
LGTM, just some minor details! Good work 💪🏻

2023-06-26 07:18 UTC, alvarobartt commented on src/argilla/client/feedback/dataset.py
> +            rprint(f"Dataset Pushed to Argilla [link={url}]{url}")
```suggestion
            rprint(f"`FeedbackDataset` -pushed to Argilla [link={url}]{name or dataset.name}[/link]")
```

2023-06-26 07:18 UTC, alvarobartt commented on src/argilla/client/feedback/dataset.py
> +        rprint(f"Dataset Pushed HuggingFace [link={url}]{url}")
```suggestion
        rprint(f"`FeedbackDataset` pushed to HuggingFace [link={url}]{repo_id}[/link]")
```

2023-06-27 10:22 UTC, krishnajalan commented
hey @alvarobartt sorry to bother but applied the suggestion and now UT is failing can you help ?

2023-06-27 10:59 UTC, davidberenstein1957 commented
Hi @krishnajalan, this was just a coincidence and not you problem. Re-running tests now.

2023-06-28 14:36 UTC, alvarobartt requested changes
LGTM, thanks for this PR @krishnajalan! Just one last minor detail, as I tried to generate the URLs and if the dataset is pushed already then the URL remains the same. Other than that, do you mind adding some unit tests to make sure that `push_to_argilla` returns a string that matches the URL format, pushing twice ends up on two different URLs based on the `argilla_id`, and that `push_to_huggingface` returns the URL in the expected format too?

2023-06-28 14:36 UTC, alvarobartt commented on src/argilla/client/feedback/dataset.py
> +            url = f"{httpx_client.base_url}/dataset/{self.argilla_id}/annotation-mode"
```suggestion
            url = f"{httpx_client.base_url}/dataset/{argilla_id or self.argilla_id}/annotation-mode"
```

2023-08-14 10:09 UTC, davidberenstein1957 commented
@krishnajalan, do you know if you'll find time to work on this matter and resolve the comments from @alvarobartt?

2023-08-31 07:54 UTC, frascuchon commented
Thanks @krishnajalan for your work. 

I think with the latest changes introduced to the feedback dataset classes. @alvarobartt can you refer to the proper PR where this was introduced? Also, it would be nice to link it to #3120. Then, we can close both, the PR and the issue.

Thanks!

2023-08-31 08:43 UTC, alvarobartt commented
Hi @frascuchon I'll take over this PR, unless @krishnajalan prefers to do so, as now the `push_to_argilla` classmethod has a return statement which is the `RemoteFeedbackDataset`, so returning the URL as a string no longer makes sense. My idea here is to print out the URL when calling `push_to_argilla`, but not returning it, as it's incompatible with the current. Anyway, remember we now have the `url` attribute for `RemoteFeedbackDataset`s, so one could easily do the following:

```python
import argilla as rg

rg.init(...)

local_dataset = rg.FeedbackDataset(...)
remote_dataset = local_dataset.push_to_argilla(name="my-dataset", workspace="my-workspace")
print(remote_dataset.url)

remote_dataset = rg.FeedbackDataset.from_argilla(name="my-dataset", workspace="my-workspace")
print(remote_dataset.url)
```

2023-08-31 08:44 UTC, closed without merging