feat: Add ```logout``` command
argilla-io/argilla pull request #3605
Opened 2023-08-21 19:22 UTC by eshwarhs

# Description

This PR adds the ```logout``` command that will allow to logout from Argilla server and remove the locally stored credentials.

Closes #3585 

**Type of change**

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested**

Tested manually in a local development environment and added tests to cover the additions and changes.

**Checklist**

- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [x] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2023-08-23 14:05 UTC, gabrielmbmb requested changes
@eshwarhs Thansk for your pull request! I wrote you some comments that needs to be addressed before we can merge this branch.

2023-08-23 14:05 UTC, gabrielmbmb commented on src/argilla/tasks/logout/__main__.py
> +    ),
For the logout we don't need any option

2023-08-23 14:05 UTC, gabrielmbmb commented on src/argilla/tasks/logout/__main__.py
> +        raise typer.Exit(code=1) from e
In the logout command we just need to:

1. Call the `init_callback` function to check that we're logged in an Argilla server https://github.com/argilla-io/argilla/blob/288df9effb5e1127f138e11d117f6a762577a4b2/src/argilla/tasks/callback.py#L21-L26
2. Call `ArgillaCredentials.remove()` and print an informative message.

2023-08-23 14:05 UTC, gabrielmbmb commented on src/argilla/client/logout.py
We don't need this module

2023-08-23 14:53 UTC, davidberenstein1957 commented
Awesome @eshwarhs, this is really useful :)

2023-08-28 07:28 UTC, gabrielmbmb approved these changes

2023-08-28 07:52 UTC, merged