feat: Improve the FeedbackDataset.__repr__ method
argilla-io/argilla pull request #4103
Opened 2023-10-31 15:48 UTC by kursathalat

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #3935 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

2023-10-31 17:05 UTC, davidberenstein1957 requested changes
Hi @kursathalat, I am not sure if the current formatting makes it more readable for me, could you try to play around with this a bit more and potentially align with the local `FeedbackDataset` and include the `metadata-properties`. Also, you left a unused import.

2023-11-08 10:40 UTC, davidberenstein1957 commented on src/argilla/client/feedback/dataset/local/dataset.py
> -        return (
@kursathalat we should just use this old default formatting but add `metadata_properties` to it.

2023-11-08 10:40 UTC, davidberenstein1957 commented on src/argilla/client/feedback/dataset/remote/dataset.py
> -        return (
@kursathalat we should just use the old default formatting as is shown for the `FeedbackDataset` but add `metadata_properties` to it.

Additionally, we need to add some tests.

2023-11-08 16:48 UTC, kursathalat commented
The problem with the current case is that when you are in a smaller screen, longer lines are wrapped improperly which looks messy. Here is the old version and new version (both looks proper on a bigger screen). If tabulate or any other library offers proper wrapping, we can iterate over the new one.

![Ekran Resmi 2023-11-08 17 37 21](https://github.com/argilla-io/argilla/assets/86690946/292f1e8f-6cb5-4c73-9097-abc3b56325d8)
![Ekran Resmi 2023-11-08 17 37 34](https://github.com/argilla-io/argilla/assets/86690946/b07614e0-f13d-4e4e-86be-183ee7450733)

2023-11-13 11:51 UTC, davidberenstein1957 commented
closing this in favour of https://github.com/argilla-io/argilla/pull/4192

2023-11-13 11:51 UTC, closed without merging