fix: Fix `prepare_dataset_for_annotation_task` to return correct format
argilla-io/argilla pull request #4397
Opened 2023-12-11 14:07 UTC by kursathalat

# Description

As described in the issue, the method returns question name for all records. In this PR, the question texts are returned so that the Alpha is correctly corrected. The method can be further improved with a better alternative.

Closes #4396 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

2023-12-11 15:15 UTC, plaguss requested changes
Thank you for tackling this @kursathalat! I think the function could be rewritten to make it more clear. For example in the loop:

```python
for responses_ in hf_dataset[question_name]:
     ...
```

Could be rewritten a bit:

```python
for row in hf_dataset:
    responses = row[question_name]
    question_text = row["text"]
```

Also, is this checked in the tests? Maybe

2023-12-11 16:29 UTC, kursathalat commented
> Thank you for tackling this @kursathalat! I think the function could be rewritten to make it more clear. For example in the loop:
> 
> ```python
> for responses_ in hf_dataset[question_name]:
>      ...
> ```
> 
> Could be rewritten a bit:
> 
> ```python
> for row in hf_dataset:
>     responses = row[question_name]
>     question_text = row["text"]
> ```
> 
> Also, is this checked in the tests?

Great, will be changing it. Currently, it is not checking the expected behavior in the test but will add some lines for that as well.

2023-12-11 18:30 UTC, plaguss approved these changes
Nice, thanks!

2023-12-13 15:37 UTC, davidberenstein1957 approved these changes

2023-12-13 15:37 UTC, merged