Add docs on how to training/inference with flair text/token-classification model
argilla-io/argilla pull request #442
Opened 2021-10-08 06:42 UTC by sakares

- [x] complete how to train text-classification docs
 - [x] complete how to train token-classification docs

2021-10-13 14:03 UTC, dvsrepo requested changes
Very good job @sakares ! Just two minor change requests

2021-10-13 14:03 UTC, dvsrepo commented on docs/guides/cookbook.ipynb
> +    "Let's read a Rubrix dataset, prepare a training set, save to `.ะปะ` for loading with flair `ColumnCorpus` and train with flair `SequenceTagger` "
I guess this supposed to be `.txt`

2021-10-13 14:03 UTC, dvsrepo commented on docs/guides/cookbook.ipynb
> +    "# Use origin prediction as label for reproduce purpose, you need to use your own label\n",
```suggestion
    "# Use original predictions as annotations for demonstration purposes, in a real use case you would use the `annotations` instead\n",
```

2021-10-13 15:03 UTC, sakares commented on docs/guides/cookbook.ipynb
> +    "Let's read a Rubrix dataset, prepare a training set, save to `.ะปะ` for loading with flair `ColumnCorpus` and train with flair `SequenceTagger` "
Alright, fixed typo

2021-10-13 15:04 UTC, sakares commented on docs/guides/cookbook.ipynb
> +    "# Use origin prediction as label for reproduce purpose, you need to use your own label\n",
Changed comment upon the suggestion

2021-10-13 18:59 UTC, dvsrepo approved these changes

2021-10-14 12:32 UTC, dcfidalgo commented
@sakares Thanks a lot for your contribution! Could you maybe rebase this branch onto our master branch? Then I think this would be good to merge.

2021-10-14 12:49 UTC, sakares commented
Hi! I am not sure if I rebase this branch with rubrix master branch correctly. I feel like I mess with something.
Pardon me for troubling around 😅

2021-10-14 14:44 UTC, dcfidalgo commented
Ok, I think I cleaned up a bit :) Could you quickly check if all your changes are still there?

2021-10-14 15:16 UTC, sakares commented
Yes, all changes are still there. Look good to me.

2021-10-14 18:49 UTC, merged

2021-10-16 06:03 UTC, sakares commented
Hi, please feel free to add the label `hacktoberfest-accepted` if this PR passes qualification. Thanks!