docs: tutorial monitoring bias and ethics
argilla-io/argilla pull request #4475
Opened 2024-01-09 16:25 UTC by sdiazlor

# Description

Include a new tutorial on monitoring bias and ethics using Giskard outputs

Closes #4447 

**Type of change**

(Remember to title the PR according to the type of change)

- [ ] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [x] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [ ] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

2024-01-09 16:26 UTC, sdiazlor commented
@davidberenstein1957 Hi, David, this is the draft version, let me know what can be improved :)

2024-01-09 16:41 UTC, davidberenstein1957 commented
Hi @sdiazlor , looking great already. 

maybe something like this would be better, also because we don't do full RLHF?
👀 Monitoring and SFT LLMs for ethics and bias using Giskard

Could you add an output example of Giskard and Langchain? This helps to understand better what is happening.

Do you think you would be able to replace the reward model part for a DPO fine-tune of Phi2 using Peft?
- https://huggingface.co/blog/dpo-trl
- https://huggingface.co/microsoft/phi-2/discussions/19
- https://github.com/mit1280/fined-tuning/blob/main/phi_2_fine_tune_using_PEFT%2Binference.ipynb
-

2024-01-10 10:27 UTC, ignacioct requested changes
Looking nice! I've made a few comments on the writing and some code, I still have to test the code. Some minor general points:

- Maybe write a conclusion afterwards, where you can wrap up the job you've done, what the user must take away, and some links to related Argilla content. 
- Some more meaningful naming for some variables, for example I'm unsure of the difference between dataset and ds, apart from the fact that they appear in different points of the tutorial. 
- Maybe generate some cell outputs so users can see how the code works.

Apart from that, maybe give it a grammar correction. I really like the writing stile, very concise and to the point.

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "In this tutorial, we explore a method to address `bias` in language models by enhancing the input data using `Reinforcement Learning with Human Feedback`. This approach aligns with ethical consi
I wouldn't write bias as code, maybe bold if you wanna highlight it.

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "2. Create an Argilla `Feedback Dataset` according to the outputs of Giskard\n",
Same here, I would write `FeedbackDataset`. As we are writing it as code, it should match our class name

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "4. Train a `reward model`"
Wouldn't put it as code, but rather with capital letters.

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +   ]
Also, don't forget final points after sentences in the list :)

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "Language models, despite their ability to perform various natural language processing tasks, often reflect biases and ethical concerns. These biases include a range of categories such as age, ge
```suggestion
    "Language models, despite their ability to perform various NLP tasks, often reflect biases and ethical concerns. These biases include a range of categories such as age, gender, race, ethnicity and others ([Huang et al., 2023](https://arxiv.org/pdf/2309.14345.pdf)), and extend to issues such as misinformation, toxicity and hallucinations.\n",
```

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "The root of these concerns lies in the fact that language models are trained on large datasets that replicate real-world characteristics, inadvertently perpetuating these biases and creating fal
Really like this sentence 👍🏼

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "Addressing these biases requires intervention that can be at different stages of model training and output generation, as suggested by several studies ([(Yeh et al., 2023)](https://aclanthology.
```suggestion
    "Addressing these biases requires intervention that can be at different stages of model training and output generation, as suggested by several studies ([(Yeh et al., 2023)](https://aclanthology.org/2023.rocling-1.37.pdf), [(Liang et al., 2021)](https://proceedings.mlr.press/v139/liang21a/liang21a.pdf), [(Garimella et al., 2021)](https://aclanthology.org/2021.findings-acl.397.pdf)). As retraining a language model is not efficient, a notable strategy is the incorporation of human feedback. In this method, the model's responses are evaluated by human annotators, and the feedback is used to develop a reward model. This reward model, in turn, guides a reinforcement learning process to adjust the parameters of the language model.\n",
```

Unsure if raters exists, we can maybe use annotators, as rating is annotating data at the end of the day

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "The essence of this approach is to make the outputs of the language model more closely match human norms and values. In this way, bias is reduced, robustness is increased, and the model's output
```suggestion
    "The essence of this approach is to match the outputs of the language model more closely with human norms and values. In this way, bias is reduced, robustness is increased, and the model's outputs are more ethically aligned and socially responsible, minimizing their potential negative impact on society."
```

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "from giskard import Dataset, Model, scan"
By convention, inside each of the blocks, we follow alphabetical order for imports. Doesn't the formatted automatically, does it? If not, is just moving around some stuff :) I can push myself the change if you are unsure.

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "Now, we will create a QA system which retrieves the data from our report and uses the LLM to answer questions. For this purpose, we will use `FAISS` which storages the chuncks of context and `La
```suggestion
    "Now, we will create a QA system, which retrieves the data from our report and uses the LLM to answer questions. For this purpose, we will use `FAISS`, for storing the chunks of context, and `LangChain`, to integrate the LLM with the retriever."
```

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "After creating the QA system, we will create a custom `Giskard.Model` object which will be used to test the LLM. After that, we [will wrap it up indicating the needed parameters](https://docs.gi
```suggestion
    "Once we have the QA system ready, we will create a custom `Giskard.Model` object which will be used to test the LLM. After that, we [will wrap it up indicating the needed parameters](https://docs.giskard.ai/en/latest/open_source/scan/scan_llm/index.html): the input `model` (our `qa_system`); the `model_type`, as working with LLM is always `text_generation`; the `name` (used as metadata); the `description` of the model used to generate the testing prompt and the `feature_names` which will be the columns of our dataset."
```

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "    for index, row in df.iterrows()\n",
```suggestion
    "    for _, row in df.iterrows()\n",
```

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "dataset = dataset.push_to_argilla(name=\"bias_dataset\", workspace=\"argilla\")"
If we push some data to argilla for annotation, we have to pull from it afterwards. If not, we are not using the annotated version.

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "dataset = dataset.push_to_argilla(name=\"bias_dataset\", workspace=\"argilla\")"
Maybe, also find more meaningful names for the datasets and dataframes than dataset and ds. It makes it easier to differentiate the variables without having additional context.

2024-01-10 10:27 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/monitoring-bias-ethics-rlhf.ipynb
> +    "    model=\"distilroberta-base\",\n",
Same here, more meaningful names for ds and task maybe

2024-01-15 17:16 UTC, davidberenstein1957 reviewed
@sdiazlor, before closing I'll also check this with "mps" on mac. We might have some m1 issues though 🥲

2024-01-15 17:34 UTC, sdiazlor commented
> @sdiazlor, before closing I'll also check this with "mps" on mac. We might have some m1 issues though 🥲

Perfect, that would be really useful!

2024-01-22 15:23 UTC, merged