[WIP] feat: create span question from SDK
argilla-io/argilla pull request #4617
Opened 2024-02-29 15:09 UTC by frascuchon

# Description

This PR introduces support for configuring feedback datasets with span questions.  A new `SpanQuestion` class is defined for that. The creation workflow would be as follows:

```python
dataset = rg.FeedbackDataset(
   fields = [rg.TextField(name="text"),...],
   questions=[rg.SpanQuestion(name="spans", title="This is the Span question", labels=["person", "org"])],
)

## You can also create label options with a different text that will shown in the annotation UI
rg.SpanQuestion(
   name="spans", 
   title="This is the Span question", 
   labels=[
      rg.SpanLabelOption(value="person", text="Person"), 
      rg.SpanLabelOption(value="org", text="Organization")
   ]
)
```

Closes https://github.com/argilla-io/argilla/issues/4616

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

Tested locally using a running instance of the Argilla server.

**Checklist**

- [ ] I added relevant documentation
- [X] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

2024-02-29 15:13 UTC, frascuchon commented
@nataliaElv I've included you as a reviewer to validate the creation workflow. Let me know if you miss something.

@burtenshaw I've included you to look at the development flow for the current SDK.

2024-03-01 08:51 UTC, jfcalvo requested changes

2024-03-01 08:51 UTC, jfcalvo commented on src/argilla/client/feedback/schemas/questions.py
> +    text: Optional[str]
I'm missing `description` as optional attribute here.

2024-03-01 09:41 UTC, frascuchon commented on src/argilla/client/feedback/schemas/questions.py
> +    text: Optional[str]
done

2024-03-01 10:59 UTC, jfcalvo approved these changes

2024-03-01 11:01 UTC, jfcalvo commented
Looks like there is a failing integration test related with span and a dataset deletion (probably because the dataset was not created well?)

2024-03-04 17:31 UTC, merged