docs: update Setfit ABSA tutorial
argilla-io/argilla pull request #4705
Opened 2024-04-08 11:11 UTC by sdiazlor

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #4695 

**Type of change**

(Remember to title the PR according to the type of change)

- [x] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [x] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [ ] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

2024-04-08 13:30 UTC, davidberenstein1957 reviewed
Looking great, some nits.

Why do we need to SpanQuestions?
Why do we use two models here?
```python
model = AbsaModel.from_pretrained(
    "sentence-transformers/paraphrase-mpnet-base-v2",
    "sentence-transformers/paraphrase-MiniLM-L6-v2",
    spacy_model="en_core_web_lg",
)
```
I feel you might need to explain `ordinal` a bit.
Perhaps we can create more catching title? Just spitballing so feel free to improve. "Enhancing sentiment classification with span based polarity predictions using SetFit" Not everyone will know aspact based sentiment analysis because it is not very descriptive IMO.

2024-04-09 10:43 UTC, ignacioct requested changes
Code looks good to me, and I found a few typos but nothing serious. Good job :)

2024-04-09 10:43 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/training-setfit-absa.ipynb
> +    "Sentiment analysis is an effective natural language processing approach for assessing the emotional tone of text. However, measuring the overall sentiment can be challenging. **Aspect-Based Sent
```suggestion
    "Sentiment analysis is an effective natural language processing approach for assessing the emotional tone of text. However, measuring the overall sentiment can be challenging. **Aspect-Based Sentiment Analysis (ABSA)** refines this task by classifying sentiments toward different detected aspects within the text. For instance, consider the sentence \"The food was great, but the service was terrible\". In this case, ABSA identifies the positive sentiment toward \"food\" and the negative sentiment towards \"service"\. This nuanced approach provides a detailed understanding of the sentiment, which is invaluable for capturing consumers' more subtle opinions about specific products or services.\n",
```

2024-04-09 10:43 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/training-setfit-absa.ipynb
> +    "3. **Polarity Classification**: This step involves assessing the sentiment associated with each identified aspect. What is the sentiment toward \"food\" and \"service\"?\n",
```suggestion
    "3. **Polarity Classification**: This step involves assessing the sentiment associated with each identified aspect. What is the sentiment towards \"food\" and \"service\"?\n",
```

2024-04-09 10:43 UTC, ignacioct commented on docs/_source/tutorials_and_integrations/tutorials/feedback/training-setfit-absa.ipynb
> +    "\n",
"what about if ..." sounds a little bit off in my head. I'd maybe change it to "what happens if ..."

2024-04-09 13:13 UTC, davidberenstein1957 approved these changes

2024-04-09 13:13 UTC, merged