refactor: move API schemas folder structure
argilla-io/argilla pull request #4954
Opened 2024-06-05 10:46 UTC by jfcalvo

# Description

This PR include changes moving API schemas to follow this structure:
```
/api
  /schemas
    /v1
      datasets.py
      records.py
      ...
```

The behavior has not been changed.

Closes #4868

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)
- [ ] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [x] Test should be passing as before.

**Checklist**

- [ ] I added relevant documentation
- [ ] follows the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-06-06 14:07 UTC, frascuchon commented on argilla/tests/unit/client/sdk/models/test_workspaces.py
> +from argilla_server.api.schemas.v1.workspaces import Workspace as ServerSchema
I think we shouldn't touch the "old" argilla client. We can just fix the server version to 1.29.0 and the code remains compatible.

2024-06-06 14:07 UTC, frascuchon commented on argilla/pyproject.toml
> +    # "argilla-server[postgresql] ~= 1.29.0"
The current argilla-server won't be compatible. We should let this fixed, even for development.

2024-06-06 14:15 UTC, frascuchon commented on argilla-server/src/argilla_server/models/database.py
> +from argilla_server.api.schemas.v1.questions import QuestionSettings
Ideally, we should avoid schema imports in core model modules.

2024-06-06 14:16 UTC, frascuchon requested changes
Same comment as handlers PR. We should remove all the changes for the `argilla` project.

2024-06-06 14:55 UTC, jfcalvo commented on argilla-server/src/argilla_server/models/database.py
> +from argilla_server.api.schemas.v1.questions import QuestionSettings
I agree. That one is needed by the infamous `Question.parsed_settings` function.

2024-06-07 10:07 UTC, frascuchon approved these changes

2024-06-07 10:48 UTC, merged