[FIX] [ENHANCEMENT] logging records in notebook without ipython
argilla-io/argilla pull request #4988
Opened 2024-06-11 10:04 UTC by burtenshaw

This PR introduces these results in a notebook environment:

![image](https://github.com/argilla-io/argilla/assets/19620375/9e1a9380-d390-4528-a0b0-154909c83798)

- tqdm shows a status bar
- non info level logging is printed with rich
- `DatasetRecords.log` returns self not `List[Record]` 
- html repr of resources is dealt with as string not ipython `HTML`

# Argilla Community Growers

Thanks for your contribution! As part of our Community Growers initiative 🌱, we're donating Justdiggit bunds in your name to reforest sub-Saharan Africa. To claim your Community Growers certificate, please contact David Berenstein in our Slack community or fill in this form https://tally.so/r/n9XrxK once your PR has been merged.

# Pull Request Templates

Please go the the `Preview` tab and select the appropriate sub-template:

* [🐞-bug](?expand=1&template=bug.md)
* [📚-documentation](?expand=1&template=docs.md)
* [🆕-features](?expand=1&template=features.md)

# Generic Pull Request Template

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #<issue_number>

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)
- [ ] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I added relevant documentation
- [ ] follows the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-06-11 10:48 UTC, frascuchon requested changes
I think we should also remove refs to IPython in `client.py`

2024-06-11 10:51 UTC, frascuchon commented on argilla-sdk/src/argilla_sdk/_helpers/_log.py
> +        if self._is_interactive() and level != "info":
Why do we include the level != "info" as part of the condition? That means nothing will be logged when running into a notebook by default, right?

2024-06-11 12:56 UTC, burtenshaw commented on argilla-sdk/src/argilla_sdk/_helpers/_log.py
> +        if self._is_interactive() and level != "info":
Yeah, we only print error and warning in notebooks. Otherwise it becomes verbose.

2024-06-12 07:54 UTC, frascuchon approved these changes

2024-06-12 07:56 UTC, frascuchon commented on argilla-sdk/src/argilla_sdk/records/_dataset_records.py
> +        return self
I think this change is making some integration tests fail. But maybe we can just this change here and create another PR to tackle https://github.com/argilla-io/argilla/issues/4947

2024-06-12 11:41 UTC, frascuchon approved these changes

2024-06-12 15:39 UTC, davidberenstein1957 approved these changes

2024-06-13 08:22 UTC, merged