[REFACTOR] `argilla-server`: rewiew OAuth owner condition
argilla-io/argilla pull request #5313
Opened 2024-07-25 14:28 UTC by frascuchon

# Description

This PR changes the behavior to detect the user role when an OAuth sign-in occurs.

- If the connected user matches the `USERNAME`, the connected user becomes an owner.
- The rest of the users will be defined as `annotator`. 
- All logic related to roles in ORG has been removed until finding a proper auth scope.

**Type of change**

- Refactor (change restructuring the codebase without changing functionality)
- Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-07-25 14:30 UTC, frascuchon commented on argilla-server/docker/argilla-hf-spaces/scripts/start.sh
> +export ARGILLA_PASSWORD="${ARGILLA_PASSWORD:-$PASSWORD}"
```suggestion
export ARGILLA_PASSWORD="${PASSWORD:-$ARGILLA_PASSWORD}"
```

2024-07-25 16:06 UTC, frascuchon commented on argilla-server/src/argilla_server/api/handlers/v1/oauth2.py
> +        raise RuntimeError("OAuth error: Missing username")
This is an unexpected error and probably the OAuth config is wrong. It will raise a 500 error

2024-07-26 09:45 UTC, jfcalvo requested changes

2024-07-26 09:45 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/errors/v1/exception_handlers.py
> +    async def authentication_error(request, exc):
```suggestion
    async def unauthorized_error(request, exc):
```

2024-07-26 09:45 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/errors/v1/exception_handlers.py
> +        return JSONResponse(status_code=status.HTTP_401_UNAUTHORIZED, content={"detail": str(exc)})
```suggestion
        return JSONResponse(
            status_code=status.HTTP_401_UNAUTHORIZED,
            # TODO: Once we move to v2.0 we can remove the content using detail attribute
            # and use the new one using code and message.
            # content={"code": exc.code, "message": exc.message},
            content={"detail": str(exc)},
        )
```

2024-07-26 09:45 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/errors/v1/exception_handlers.py
> +    async def authentication_error(request, exc):
I would move this exception handler to be the first one (with the rest of generic errors) following the order of the status code, in this case `401`.

2024-07-26 09:45 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/handlers/v1/oauth2.py
> +        raise RuntimeError("OAuth error: Missing username")
then do you think it's ok to don't check for that condition and let it crash on line 81?

2024-07-29 06:33 UTC, frascuchon commented on argilla-server/src/argilla_server/api/handlers/v1/oauth2.py
> +        raise RuntimeError("OAuth error: Missing username")
No, I prefer to raise this error instead of a validation one.

2024-07-29 06:37 UTC, frascuchon commented on argilla-server/src/argilla_server/api/errors/v1/exception_handlers.py
> +    async def authentication_error(request, exc):
We have all error handler's names aligned with the exception class names. I will keep this aligned too.

2024-07-29 10:58 UTC, jfcalvo approved these changes

2024-07-29 11:00 UTC, merged