Add custom subdomain `CNAME`
argilla-io/argilla pull request #5328
Opened 2024-07-29 15:28 UTC by davidberenstein1957

# Description

Closes #5327 

**Type of change**

- Documentation update

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-07-29 16:19 UTC, davidberenstein1957 commented
After merging, we should update the DNS

2024-07-29 16:24 UTC, frascuchon commented on argilla-frontend/nuxt.config.ts
> +    documentationSite: "https://docs.v1.argilla.io/",
Should be the `https://docs.v1.argilla.io/` reachable?

2024-07-29 16:24 UTC, frascuchon commented
Maybe [this one](https://github.com/argilla-io/argilla/pull/5321) is related

2024-07-29 16:24 UTC, davidberenstein1957 commented on argilla-frontend/nuxt.config.ts
> +    documentationSite: "https://docs.v1.argilla.io/",
Yes it should be after the DNS updates.

2024-07-29 16:29 UTC, frascuchon commented
I think this PR should be merged after the publishing of the release (at least changes related to the docs) What do you think? Could we let UI links pointing the current `argilla-io.....` domain and let github make the redirection? (Just to apply these changes after the release)

2024-07-29 16:32 UTC, davidberenstein1957 commented
> I think this PR should be merged after the publishing of the release (at least changes related to the docs) What do you think? Could we let UI links pointing the current `argilla-io.....` domain and let github make the redirection? (Just to apply these changes after the release)

I agree @frascuchon. I also found https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7.

2024-07-29 16:33 UTC, davidberenstein1957 commented
@frascuchon is this fixing the tests? https://github.com/argilla-io/argilla/pull/5330

2024-07-30 09:00 UTC, frascuchon commented on argilla-frontend/nuxt.config.ts
> +      "https://docs.v1.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html#setting-up-persistent-storage",
If the product points to the new docs, Should not be the docs.argilla.io?

2024-07-30 09:02 UTC, frascuchon commented on argilla-server/src/argilla_server/_app.py
> +            "    https://docs.v1.argilla.io/en/latest/reference/telemetry.html\n\n"
why does this point to the old documentation?

2024-07-30 09:05 UTC, frascuchon commented on argilla/docs/CNAME
> +docs.v1.argilla.io
should not be the `docs.argilla.io` ?

2024-07-30 09:09 UTC, frascuchon commented on CONTRIBUTING.md
> +For more seasoned contributors, we recommend taking a look at the [contributor section](https://docs.v1.argilla.io/en/latest/community/contributing.html) in our docs.
docs.argilla.io?

2024-07-30 09:29 UTC, dvsrepo requested changes
I don't have additional comments to those of @frascuchon

2024-07-30 09:32 UTC, frascuchon commented
> @frascuchon is this fixing the tests? #5330

Tests were fixed in https://github.com/argilla-io/argilla/pull/5331

2024-07-30 10:07 UTC, frascuchon approved these changes

2024-07-30 10:10 UTC, merged