[ENHANCEMENT] `argilla server`: Add support for filter on list datasets
argilla-io/argilla pull request #5374
Opened 2024-08-02 12:48 UTC by frascuchon

# Description

This PR adds filter support to list user datasets endpoint. The endpoint allows filterirng by `status` and `name`. This can be used by clients when filtering by datasets.

**Type of change**

- Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-09-03 11:30 UTC, jfcalvo requested changes

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/tests/unit/api/handlers/v1/datasets/test_list_user_datasets.py
> +class TestListUserDatasets:
```suggestion
class TestListCurrentUserDatasets:
```

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/tests/unit/api/handlers/v1/datasets/test_list_user_datasets.py
The name of the file should be changes to `test_list_current_user_datasets.py`

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/tests/unit/api/handlers/v1/datasets/test_list_user_datasets.py
I miss additional tests:
* One checking that the order is the expected one.
* Another one checking filtering by `workspace_id`.

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/tests/unit/api/handlers/v1/datasets/test_list_user_datasets.py
> +    async def test_list_user_datasets_by_name(self, async_client: AsyncClient, owner_auth_header: dict):
```suggestion
    async def test_list_current_user_datasets_by_name(self, async_client: AsyncClient, owner_auth_header: dict):
```

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/tests/unit/api/handlers/v1/datasets/test_list_user_datasets.py
> +    async def test_list_user_datasets_by_status(self, async_client: AsyncClient, owner_auth_header: dict):
```suggestion
    async def test_list_current_user_datasets_by_status(self, async_client: AsyncClient, owner_auth_header: dict):
```

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/tests/unit/api/handlers/v1/datasets/test_list_user_datasets.py
> +    async def test_list_user_datasets_by_status_and_name(self, async_client: AsyncClient, owner_auth_header: dict):
```suggestion
    async def test_list_current_user_datasets_by_status_and_name(self, async_client: AsyncClient, owner_auth_header: dict):
```

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/datasets.py
> +    query = select(Dataset).filter_by(**filters)
Is not possible to define the order here?

```suggestion
    query = select(Dataset).filter_by(**filters).order_by(Dataset.inserted_at.asc())
```

So you can remove the line before the return.

2024-09-03 11:30 UTC, jfcalvo commented on argilla-server/src/argilla_server/models/database.py
> -    datasets: Mapped[List["Dataset"]] = relationship(
Why deleting it?

2024-09-17 07:53 UTC, frascuchon commented on argilla-server/src/argilla_server/models/database.py
> -    datasets: Mapped[List["Dataset"]] = relationship(
We don't need this attribute anymore. We fetch user datasets based on the query built in the `datasets.list_datasets` method, which accepts an optional `user` argument

2024-09-17 14:12 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/accounts.py
>              f"Cannot delete the workspace {workspace.id}. This workspace has some feedback datasets linked"
```suggestion
            f"Cannot delete the workspace {workspace.id}. This workspace has some datasets linked"
```

2024-09-17 14:23 UTC, jfcalvo commented on argilla-server/src/argilla_server/models/database.py
> -    datasets: Mapped[List["Dataset"]] = relationship(
Ok, but it's fine to left the association there in case it's useful from the console, tests, etc.

2024-09-17 14:30 UTC, frascuchon commented on argilla-server/src/argilla_server/models/database.py
> -    datasets: Mapped[List["Dataset"]] = relationship(
We're not using anywhere this value. I'd prefer to remove unused code.

2024-09-18 07:15 UTC, jfcalvo approved these changes

2024-09-18 07:25 UTC, merged