[FEAT] argilla server: add basic endpoints telemetry support
argilla-io/argilla pull request #5437
Opened 2024-08-28 10:59 UTC by frascuchon

# Description

This PR adds a middleware component to track the API endpoint's usage.

**Type of change**

- New feature (non-breaking change which adds functionality)
- Refactor (change restructuring the codebase without changing functionality)
- Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-08-29 07:19 UTC, frascuchon commented on argilla-server/tests/unit/test_endpoints_telemetry.py
> +    def test_not_track_endpoint_call_with_telemetry_disabled(self, test_telemetry: TelemetryClient):
```suggestion
    def test_not_track_endpoint_call_with_disabled_telemetry(self, test_telemetry: TelemetryClient):
```

2024-08-29 15:31 UTC, jfcalvo requested changes

2024-08-29 15:31 UTC, jfcalvo commented on argilla-server/src/argilla_server/_app.py
> +    """
```suggestion
    """
```

2024-08-29 15:31 UTC, jfcalvo commented on argilla-server/src/argilla_server/_app.py
> +        return
What do you think about moving this to the `configure_telemetry(app)` call so we avoid checking it on every request?

Something like:

```python
if settings.enable_telemetry:
    configure_telemetry(app)
```

2024-08-29 15:31 UTC, jfcalvo commented on argilla-server/src/argilla_server/_app.py
> +            endpoint_path = resolve_endpoint_path_for_request(request)
Why not moving this logic to be inside the telemetry client? With that you can pass only `request` and `response` like:

```python
await get_telemetry_client().track_endpoint(request, response)
```

2024-08-29 15:31 UTC, jfcalvo commented on argilla-server/src/argilla_server/_app.py
> +    async def track_api_endpoint(request: Request, call_next):
I believe a better naming could be something like:

```suggestion
    async def track_api_request(request: Request, call_next):
```

2024-08-29 15:31 UTC, jfcalvo commented on argilla-server/src/argilla_server/_app.py
> +                await get_telemetry_client().track_endpoint(
```suggestion
                await get_telemetry_client().track_api_request(
```

2024-08-29 15:43 UTC, frascuchon commented on argilla-server/src/argilla_server/_app.py
> +        return
The `configure_telemetry` function will be called once when FastAPI is created, not for every request. If telemetry is disabled, the telemetry middleware won't be loaded.

2024-08-29 15:45 UTC, frascuchon commented on argilla-server/src/argilla_server/_app.py
> +            endpoint_path = resolve_endpoint_path_for_request(request)
Yes, I thought about this when developing it. It makes sense and the middleware keeps simpler. I will push the changes

2024-09-02 09:40 UTC, jfcalvo approved these changes

2024-09-02 09:40 UTC, jfcalvo commented on argilla-server/tests/unit/api/handlers/v1/test_datasets.py
> +    @pytest.mark.skip
Why we need to skip these tests?

2024-09-02 09:46 UTC, frascuchon commented on argilla-server/tests/unit/api/handlers/v1/test_datasets.py
> +    @pytest.mark.skip
I needed to build the docker image. Those tests are failing in the base branch. I review all of them in a separate PR.

2024-09-02 09:46 UTC, merged