[PERF] argilla server: Reduce general transaction time
argilla-io/argilla pull request #5609
Opened 2024-10-17 21:37 UTC by frascuchon

# Description

- Remove unnecessary extra SAVEPOINTS
- Move out of the commit all search index operations
- ~~the refresh parameter for es can be set to `wait_for` instead of `true` since index operations are out of transactions. This will help with the es performance.~~

**Type of change**

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Refactor (change restructuring the codebase without changing functionality)
- Improvement (change adding some improvement to an existing functionality)
- Documentation update

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-10-17 21:38 UTC, frascuchon commented on argilla-server/src/argilla_server/bulk/records_bulk.py
> +
```suggestion
```

2024-10-17 22:12 UTC, frascuchon commented on argilla-server/src/argilla_server/contexts/datasets.py
> +from attr import attributes
```suggestion
```

2024-10-18 12:33 UTC, jfcalvo requested changes

2024-10-18 12:33 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/datasets.py
> -            await record.dataset.awaitable_attrs.vectors_settings
You didn't move this line. Is not needed anymore?

2024-10-18 12:33 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/distribution.py
> +    )
Why is this needed now?

2024-10-18 12:33 UTC, jfcalvo commented on argilla-server/src/argilla_server/models/mixins.py
> +        cls, db: AsyncSession, where: List["BinaryExpression"], autocommit: bool = True
We're using `conditions` in other functions:

```suggestion
        cls, db: AsyncSession, conditions: List["BinaryExpression"], autocommit: bool = True
```

2024-10-18 12:33 UTC, jfcalvo commented on argilla-server/src/argilla_server/search_engine/elasticsearch.py
> +        await self.client.update(index=index_name, id=id, **body, refresh="wait_for")
Why not use `false` here?

> Take no refresh related actions. The changes made by this request will be made visible at some point after the request returns.

We can wait I guess.

2024-10-18 12:40 UTC, frascuchon commented on argilla-server/src/argilla_server/search_engine/elasticsearch.py
> +        await self.client.update(index=index_name, id=id, **body, refresh="wait_for")
By setting `refresh=False` the front-end may fail since they have some internal logic assuming that the records are ready for searches immediately after (for example, after bulk responses).

We should to sync with them to apply the change safely.

2024-10-18 12:41 UTC, frascuchon commented on argilla-server/src/argilla_server/contexts/datasets.py
> -            await record.dataset.awaitable_attrs.vectors_settings
Nope. This line was not necessary since this is done inside the `_preload_record_relation_ships_before_index` function

2024-10-18 13:47 UTC, frascuchon commented on argilla-server/src/argilla_server/contexts/distribution.py
> +    )
Since we're moving the [_preload_records_relationships_before_index call](https://github.com/argilla-io/argilla/pull/5609/files#diff-8b6a4a23212d32e0db897e0fd54b482d2246be5f98c24915ce4f93923f14e8d5L66) before the search index, the records info must be loaded before the new status is computed. Indeed, this worked because of the side effect of the preload for the index.

2024-10-23 10:08 UTC, jfcalvo approved these changes

2024-10-23 12:22 UTC, merged