Adding Functionality To Update Users
argilla-io/argilla pull request #5615
Opened 2024-10-18 23:42 UTC by sean-hickey-wf

# Description
Argilla offers the ability to create and delete users but not the ability to update a User object after it has been created. For example, if we want to update the Role of a user after they have been created (from annotator to admin for example), this is not possible without deleting and recreating the User. 

This PR adds an update endpoint to the FastAPI server and also the convenience of doing this through the python sdk also
Closes #<issue_number>

**Type of change**

- New feature (non-breaking change which adds functionality)
- Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**
Tests have been added at both the server and SDK level to ensure that the update method is working as expected

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-10-28 15:07 UTC, frascuchon reviewed
Great! Thanks @sean-hickey-wf !!!

Could you please update the [image used](https://github.com/sean-hickey-wf/argilla/blob/feat/add-update-user-functionality/.github/workflows/argilla.yml#L24) in the SDK integration tests to run them with the new changes? 

```yaml
      argilla-server:
        image: argilladev/argilla-hf-spaces:pr-5615
```

2024-10-28 16:02 UTC, jfcalvo reviewed
Hi @sean-hickey-wf thank you very much for your contribution ❤️ . I have added some small comments in case you want to apply them.

2024-10-28 16:02 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/users.py
> +    first_name: Optional[constr(min_length=1, strip_whitespace=True)]
You could annotate the fields so we can reutilize them on `UserCreate` and `UserUpdate` (avoiding duplication). You can take a look to some other schemas where we are doing something similar, i.e. `MetadataPropertyName`.

As example:

```python
UserFirstName = Annotated[
    constr(min_length=1, strip_whitespace=True),
    Field(..., description="The first name for the user")
]

class UserCreate(BaseModel):
    first_name: UserFirstName

class UserUpdate(BaseModel):
    first_name: Optional[UserFirstName]
```

You can do something similar to the rest of the fields.

2024-10-28 16:02 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/users.py
> +    password: Optional[str]
Don't forget to apply the missing validations for these fields too.

2024-10-28 16:02 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/accounts.py
> +    return await user.update(db, **params)
We're moving away from using schemas on contexts files so receiving a dictionary with the attributes would be a good idea:

```suggestion
async def update_user(db: AsyncSession, user: User, user_attrs: dict) -> User:
    return await user.update(db, **user_attrs)
```

You can move the `user_update.dict(exclude_unset=True)` to pass the `user_attrs` to the handler.

2024-10-28 17:49 UTC, sean-hickey-wf commented
@frascuchon @jfcalvo thanks for the review! Will make those changes tonight or tomorrow 😄 
If you think of anything else in the meantime lemme know!

2024-11-05 14:22 UTC, frascuchon commented
@sean-hickey-wf, let me know if you need help with this PR

2024-11-16 20:15 UTC, sean-hickey-wf commented on argilla-server/src/argilla_server/api/schemas/v1/users.py
> +    first_name: Optional[constr(min_length=1, strip_whitespace=True)]
This has been added now!

2024-11-16 20:16 UTC, sean-hickey-wf commented on argilla-server/src/argilla_server/contexts/accounts.py
> +    return await user.update(db, **params)
All good 👍 You've gotten the validation already when hitting the API so yeah this change makes sense to just pass around the dict

2024-11-16 20:32 UTC, sean-hickey-wf commented
> @sean-hickey-wf, let me know if you need help with this PR

@frascuchon @jfcalvo sorry this took so long, was swamped in work! I've made the changes requested but I having trouble getting the env set up to make sure the tests are passing. If one of ye could just check that everything looks sensible and make sure the tests pass we should be good to go!

2024-11-19 15:01 UTC, frascuchon commented on argilla-server/tests/unit/api/handlers/v1/users/test_update_user.py
> +        response = await async_client.put(
```suggestion
        response = await async_client.patch(
```

2024-11-19 15:01 UTC, frascuchon commented on argilla-server/tests/unit/api/handlers/v1/users/test_update_user.py
> +        response = await async_client.put(
```suggestion
        response = await async_client.patch(
```

2024-11-19 15:01 UTC, frascuchon commented on argilla-server/tests/unit/api/handlers/v1/users/test_update_user.py
> +        response = await async_client.put(
```suggestion
        response = await async_client.patch(
```

2024-11-19 15:01 UTC, frascuchon commented on argilla-server/tests/unit/api/handlers/v1/users/test_update_user.py
> +        response = await async_client.put(
```suggestion
        response = await async_client.patch(
```

2024-11-19 15:02 UTC, frascuchon commented on argilla-server/tests/unit/api/handlers/v1/users/test_update_user.py
> +        response = await async_client.put(
```suggestion
        response = await async_client.patch(
```

2024-11-19 15:02 UTC, frascuchon commented on argilla-server/tests/unit/api/handlers/v1/users/test_update_user.py
> +        response = await async_client.put(
```suggestion
        response = await async_client.patch(
```

2024-11-19 15:03 UTC, frascuchon requested changes
I left some suggestions. I think those are the reasons why tests are failing.

2024-11-27 13:18 UTC, sean-hickey-wf commented
> I left some suggestions. I think those are the reasons why tests are failing.

@frascuchon sorry I meant to come back to this and fix it this week! Thanks for pushing those changes. Patches make more sense than Puts 👍

2024-12-02 11:09 UTC, frascuchon commented on .github/workflows/argilla.yml
> +        image: argilladev/argilla-hf-spaces:pr-5615
Rollback the tag version
```suggestion
        image: argilladev/argilla-hf-spaces:develop
```

2024-12-02 11:41 UTC, jfcalvo requested changes

2024-12-02 11:41 UTC, jfcalvo commented on argilla-server/CHANGELOG.md
> +- API endpoint added to the User router to allow updates to User objects ([#5614](https://github.com/argilla-io/argilla/issues/5614))
We usually link to the PR with the changes.
```suggestion
- API endpoint added to the User router to allow updates to User objects ([#5615](https://github.com/argilla-io/argilla/pull/5615))
```

2024-12-02 11:41 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/handlers/v1/users.py
> +    return await accounts.update_user(db, user, user_update.dict(exclude_unset=True))
As we moved to Pydantic v2 we should use `model_dump` instead of `dict`:
```suggestion
    return await accounts.update_user(db, user, user_update.model_dump(exclude_unset=True))
```

2024-12-02 11:41 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/users.py
> +    password: Optional[UserPassword] = None
@frascuchon should we use here `UpdateSchema` mixin so we avoid setting null values for some of these attributes?

2024-12-02 11:41 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/accounts.py
> +    return await user.update(db, **user_attrs, autocommit=True)
`autocommit` is already `True` by default:

```suggestion
    return await user.update(db, **user_attrs)
```

2024-12-02 11:41 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/accounts.py
> +        user_attrs["password_hash"] = hash_password(user_attrs.pop("password"))
We should have a test covering the password update.

2024-12-02 12:29 UTC, frascuchon commented on argilla-server/src/argilla_server/contexts/accounts.py
> +        user_attrs["password_hash"] = hash_password(user_attrs.pop("password"))
Done

2024-12-02 12:32 UTC, frascuchon commented on argilla-server/src/argilla_server/api/schemas/v1/users.py
> +    __non_nullable_fields__ = {"first_name", "username", "role", "password"}
`last_name` could be nullable

2024-12-02 14:57 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/users.py
> +    __non_nullable_fields__ = {"first_name", "username", "role", "password"}
We usually set `__non_nullable_fields__` after defining the attributes but I think it's ok this way too.

2024-12-02 15:13 UTC, jfcalvo approved these changes
Amazing contribution! 💪 

Thank you very much.

2024-12-02 15:15 UTC, sean-hickey-wf commented
@jfcalvo @frascuchon thank you for helping finish this off!

2024-12-03 08:29 UTC, frascuchon approved these changes
Thanks for this great contribution, @sean-hickey-wf!

2024-12-03 08:29 UTC, merged