[DRAFT] [FEATURE-BRANCH] feat: add dataset export to Hub
argilla-io/argilla pull request #5709
Opened 2024-11-22 11:26 UTC by jfcalvo

# Description

This PR adds a new endpoint to support exporting an Argilla dataset to HuggingFace Hub.

Being the endpoint `POST /api/v1/datasets/:dataset_id/export` with the following expected body:
- `name`: the name of the dataset to be created on HF Hub. i.e. `dumdumpacheco/my-new-dataset`.
- `subset` (optional, default: `default`): the subset of the dataset to be created.
- `split` (optional, default: `train`): the split of the dataset to be created.
- `private` (optional, default: `false`): whether the dataset should be private or not.
- `token`: the HF Hub API access token to create the dataset, it should have WRITE access.

**Type of change**

- New feature (non-breaking change which adds functionality)

**How Has This Been Tested**

- [ ] Testing manually exporting some datasets.

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-11-22 11:28 UTC, jfcalvo commented on argilla-server/pyproject.toml
> +    "huggingface-hub>=0.26.2",
<del>This is probably not necessary. I added the change thinking that we need to use the library for the export somehow.</del>

2024-11-22 12:21 UTC, jfcalvo commented
@damianpumar this draft can be useful for you.

2024-11-29 15:41 UTC, jfcalvo commented on argilla-server/pyproject.toml
> +    "huggingface-hub>=0.26.2",
At the end I'm using `huggingface-hub` package.

@frascuchon do you think it's ok to have the dependency update to this more recent version?

2024-12-02 08:34 UTC, jfcalvo commented on argilla-server/pyproject.toml
> +    "Jinja2>=3.1.4",
Add comment about this used by hugging face-hub package.

2024-12-02 08:39 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/hub.py
> +        self.version = uuid4()
```suggestion
        self.cache_version = uuid4()
```

2024-12-02 08:40 UTC, jfcalvo commented on argilla-server/src/argilla_server/contexts/hub.py
> +        self.version = uuid4()
Take a look if we have a proper way to disable cache.

2024-12-03 11:00 UTC, frascuchon commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    token: str
Add a validation here to avoid sending empty tokens

2024-12-03 11:02 UTC, frascuchon commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    name: str
Add validation to avoid empty names. Should we also add a validation to check name format <owner>/<dataset>?

2024-12-03 11:05 UTC, frascuchon commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    split: Optional[str] = "train"
Are valid other values for split than `train`, `validation` and `test`?

2024-12-03 12:51 UTC, frascuchon commented on argilla-server/src/argilla_server/database.py
> +SyncSessionLocal = sessionmaker(autocommit=False, expire_on_commit=False, bind=sync_engine)
To reuse same session when running in the same thread, we could define local session as an scoped session See the [docs](https://docs.sqlalchemy.org/en/20/orm/contextual.html#using-custom-created-scopes)

2024-12-03 12:54 UTC, frascuchon commented on argilla-server/src/argilla_server/api/handlers/v1/datasets/datasets.py
> +    job = hub_jobs.export_dataset_to_hub_job.delay(
It would be nice if we avoid exporting empty datasets. Also, I think in those cases, the export job will systematically fail.

2024-12-03 12:58 UTC, frascuchon requested changes
I miss some tests regarding the REST endpoint.

Also, it would be nice if we could have a set of tests running the export job directly. Creating a dataset manually, maybe?

2024-12-03 15:12 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    name: str
Not sure about adding a check for a specific format.

2024-12-03 15:13 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    split: Optional[str] = "train"
It's a free field right?

2024-12-03 15:14 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/handlers/v1/datasets/datasets.py
> +    job = hub_jobs.export_dataset_to_hub_job.delay(
It's possible to export an empty dataset. Do you think we should avoid them at all?

2024-12-03 15:40 UTC, frascuchon commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    split: Optional[str] = "train"
Not sure, this is why I'm asking it :-)

2024-12-03 15:49 UTC, frascuchon commented on argilla-server/src/argilla_server/api/handlers/v1/datasets/datasets.py
> +    job = hub_jobs.export_dataset_to_hub_job.delay(
Exporting empty datasets raises an error since features are inferred by the first row. You can try with an empty dataset created on your test space

 ```bash
5:48:20 worker_default.1 | [12/03/24 15:48:20] ERROR    ERROR:rq.worker:[Job                 worker.py:1503
15:48:20 worker_default.1 |                              7cdc401c-f226-4af2-80c2-00241e501dc8               
15:48:20 worker_default.1 |                              ]: exception raised while executing                
15:48:20 worker_default.1 |                              (argilla_server.jobs.hub_jobs.export               
15:48:20 worker_default.1 |                              _dataset_to_hub_job)                               
15:48:20 worker_default.1 |                              Traceback (most recent call last):                 
15:48:20 worker_default.1 |                                File                                             
15:48:20 worker_default.1 |                              "/opt/venv/lib/python3.13/site-packa               
15:48:20 worker_default.1 |                              ges/datasets/builder.py", line 1634,               
15:48:20 worker_default.1 |                              in _prepare_split_single                           
15:48:20 worker_default.1 |                                  num_examples, num_bytes =                      
15:48:20 worker_default.1 |                              writer.finalize()                                  
15:48:20 worker_default.1 |                                                            ~~~~~~               
15:48:20 worker_default.1 |                              ~~~~~~~~~^^                                        
15:48:20 worker_default.1 |                                File                                             
15:48:20 worker_default.1 |                              "/opt/venv/lib/python3.13/site-packa               
15:48:20 worker_default.1 |                              ges/datasets/arrow_writer.py", line                
15:48:20 worker_default.1 |                              648, in finalize                                   
15:48:20 worker_default.1 |                                  raise                                          
15:48:20 worker_default.1 |                              SchemaInferenceError("Please pass                  
15:48:20 worker_default.1 |                              `features` or at least one example                 
15:48:20 worker_default.1 |                              when writing data")                                
15:48:20 worker_default.1 |                              datasets.arrow_writer.SchemaInferenc               
15:48:20 worker_default.1 |                              eError: Please pass `features` or at               
15:48:20 worker_default.1 |                              least one example when writing data   
```

2024-12-04 09:18 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    token: str
Done.

2024-12-04 09:18 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    name: str
I added validation to avoid empty names.

2024-12-04 09:19 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/handlers/v1/datasets/datasets.py
> +    job = hub_jobs.export_dataset_to_hub_job.delay(
Added a validation on the handler raising a 422 error when there is no records for the dataset.

2024-12-04 09:31 UTC, jfcalvo commented on argilla-server/src/argilla_server/api/schemas/v1/datasets.py
> +    split: Optional[str] = "train"
It's certainly a free text parameter, with some additional features like allowing splits/slices. You can see here an example using "freetext" [here](https://huggingface.co/datasets/jfcalvo/export-testing-different-split).

2024-12-04 09:32 UTC, jfcalvo commented
> I miss some tests regarding the REST endpoint.
> 
> Also, it would be nice if we could have a set of tests running the export job directly. Creating a dataset manually, maybe?

I will try to add tests for the job in a different PR.

2024-12-04 11:09 UTC, jfcalvo commented on argilla-server/src/argilla_server/database.py
> +SyncSessionLocal = sessionmaker(autocommit=False, expire_on_commit=False, bind=sync_engine)
Done. Using `scoped_session`.

2024-12-04 12:29 UTC, frascuchon approved these changes
Nice!

2024-12-04 12:31 UTC, merged