`argilla-server` feat: add test suite for `HubDatasetExporter`
argilla-io/argilla pull request #5740
Opened 2024-12-05 16:02 UTC by jfcalvo

# Description

This PR includes a suite of tests for `HubDatasetExporter` class, checking the most common scenarios for exporting datasets from Argilla to the Hub.

**Type of change**

- Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

- [ ] Running the test suite. Writing the last examples I got a rate-limiting error so I will try to run them on GitHub.

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

2024-12-10 14:16 UTC, frascuchon commented on argilla-server/tests/unit/contexts/hub/test_hub_dataset_exporter.py
> +
Why not prepare the test session here instead of defining a `async_client` argument, which can be hard to understand?

```suggestion
from argilla_server.contexts import hub 

@pytest.fixture
def test_sync_db():
   session = SyncTestSession()
   
   def override_get_sync_db():
        yield session

   mocker.patch.object(hub, "get_sync_db", override_get_sync_db)

   yield session
```

2024-12-10 14:20 UTC, frascuchon commented on argilla-server/tests/unit/contexts/hub/test_hub_dataset_exporter.py
> +        assert exported_dataset[0] == {
I think it would be nice to add some tests adding suggestions

2024-12-10 14:33 UTC, frascuchon requested changes
Review the comments on tests

2024-12-10 15:24 UTC, jfcalvo commented on argilla-server/tests/unit/contexts/hub/test_hub_dataset_exporter.py
> +
Ok, let's move it to the test.

2024-12-10 16:32 UTC, jfcalvo commented on argilla-server/tests/unit/contexts/hub/test_hub_dataset_exporter.py
> +        assert exported_dataset[0] == {
We will do it in another PR once we agree into add suggestions to the export (and maybe date times as well).

2024-12-11 08:23 UTC, frascuchon approved these changes
Nice work!

2024-12-11 08:43 UTC, merged