Fix/edit labeling tutorial
argilla-io/argilla pull request #750
Opened 2021-12-02 14:42 UTC by leireropl

Edits based on issue 716. Added some format improvements and some grammar improvements, too.

2021-12-02 15:23 UTC, dvsrepo commented
Would it be possible to update the images to the latest UI too? If it's not possible for all of them we could remove some of them

2021-12-02 16:07 UTC, leireropl commented
> Would it be possible to update the images to the latest UI too? If it's not possible for all of them we could remove some of them

Yes, absolutely. I wanted to ask you how did you record/edit videos and pictures. I will text you tomorrow, then :)

2021-12-03 09:25 UTC, dcfidalgo requested changes
Thanks a lot! I made a few inline suggestions. Also, could you do a rebase on the master branch to avoid merge conflicts? Maybe it would be best to first merge the other open PR, and then this one, since both will modify the same file.

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "## Setup Rubrix and install tutorial dependencies\n",
Here i would prefer just "Setup":
```suggestion
    "## Setup\n",
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "\n",
I think we can just drop this sentence
```suggestion
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "In addition to this, the `transformers` and `datasets` libraries must be imported, as they are the main libraries for this tutorial:"
```suggestion
    "In addition to this, the `transformers` and `datasets` libraries must be installed, which we will use to retrieve the data and the model."
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
>      "%pip install sklearn -qqq"
```suggestion
    "# install dependencies for this tutorial\n",
    "%pip install transformers[torch] datasets sklearn -qqq"
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "1. A **dataset** in the banking domain: `banking77` [(https://huggingface.co/datasets/banking77)](https://huggingface.co/datasets/banking77)\n",
```suggestion
    "1. A **dataset** in the banking domain: [banking77](https://huggingface.co/datasets/banking77)\n",
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "2. A **pre-trained sentiment classifier**: `distilbert-base-uncased-finetuned-sst-2-english` [(https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)](https://huggingface.co/dis
```suggestion
    "2. A **pre-trained sentiment classifier**: [distilbert-base-uncased-finetuned-sst-2-english](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)\n",
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "As a first step, let's use the pre-trained model for predicting over our raw dataset. Thus, we will use the handy `dataset.map` method from the `datasets` library.\n",
```suggestion
    "As a first step, let's use the pre-trained model for predicting over our raw dataset. For this, we will use the handy `dataset.map` method from the `datasets` library.\n",
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "The following script builds a list of Rubrix records with the predictions and logs them into a Rubrix Dataset. We'll use this dataset to explore and label our first training set."
script is usually associated to a proper file, i think code is fine here
```suggestion
    "The following code builds a list of Rubrix records with the predictions and logs them into a Rubrix Dataset. We'll use this dataset to explore and label our first training set."
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "Rubrix provides you with a search-driven UI to annotated data, using **free-text search**, **search filters** and **the Elasticsearch query DSL** for advanced queries. This is super useful for s
```suggestion
    "Rubrix provides you with a search-driven UI to annotated data, using **free-text search**, **search filters** and **the Elasticsearch query DSL** for advanced queries. This is especially useful for sparse datasets, tasks with a high number of labels, or unbalanced classes. In the standard case, we recommend you to follow the workflow below:\n",
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "## 4. Test the fine-tuned model\n",
Below you used the present participle ("Adding", "Training"), so i would use it here, too
 ```suggestion
    "## 4. Testing the fine-tuned model\n",
```

2021-12-03 09:25 UTC, dcfidalgo commented on docs/tutorials/01-labeling-finetuning.ipynb
> +    "In this tutorial, you have learnt how to build a training set from scratch with the help of a pre-trained model, performing two iterations of `predict` > `log` > `label`. \n",
```suggestion
    "In this tutorial, you learned how to build a training set from scratch with the help of a pre-trained model, performing two iterations of `predict` > `log` > `label`. \n",
```

2021-12-03 15:20 UTC, leireropl commented
I think I committed all changes. Will do the images and rebasing next day!

2021-12-09 11:32 UTC, dcfidalgo approved these changes

2021-12-09 12:34 UTC, merged